# Generated by Django 4.2.1 on 2023-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='id_film',
            new_name='film',
        ),
        migrations.AlterField(
            model_name='movies',
            name='filf_genre',
            field=models.CharField(max_length=50, verbose_name='Жанр'),
        ),
    ]
