# Generated by Django 4.2.1 on 2023-05-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_movies_duration_alter_movies_end_show_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='name_film',
        ),
    ]
