# Generated by Django 4.2.1 on 2023-05-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_movies_options_alter_session_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.IntegerField(verbose_name='Кол-во рядов')),
                ('number_seats', models.IntegerField(verbose_name='Кол-во мест в ряду')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Время')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(default='45 минут', max_length=50, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='end_show',
            field=models.DateField(verbose_name='Конец проката'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='filf_genre',
            field=models.CharField(default='Комедия', max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='film_description',
            field=models.TextField(default='Хороший фильм', max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='film_photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='film_title',
            field=models.CharField(default='LAZANI', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='in_cinemas',
            field=models.BooleanField(default=False, verbose_name='В прокате сейчас'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='start_show',
            field=models.DateField(verbose_name='Начало проката'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AddField(
            model_name='sessions',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.movies'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.halls'),
        ),
    ]
