# Generated by Django 4.2.1 on 2023-05-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_tickets_session_alter_sessions_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='film_title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together={('room', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('seat', 'row')},
        ),
    ]
