# Generated by Django 4.2.1 on 2023-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_movies_film_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='name',
            field=models.CharField(default='na', max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
