# Generated by Django 4.2.1 on 2023-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_halls_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='name',
            field=models.CharField(default='Классик', max_length=30, unique=True, verbose_name='Название'),
        ),
    ]
