# Generated by Django 4.2.1 on 2023-05-27 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_halls_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numb', models.ForeignKey(max_length=11, on_delete=django.db.models.deletion.PROTECT, to='films.buyer', verbose_name='Номер покупателя')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.tickets', verbose_name='ID билета')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
            },
        ),
        migrations.AddField(
            model_name='buyer',
            name='historyb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.history', verbose_name='ID истории'),
        ),
    ]
