# Generated by Django 4.2.1 on 2023-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_buyer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='phone_numb',
        ),
        migrations.RemoveField(
            model_name='history',
            name='ticket',
        ),
        migrations.AddField(
            model_name='tickets',
            name='phone_number',
            field=models.CharField(default=11111111, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
