# Generated by Django 4.2.1 on 2023-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_remove_history_phone_numb_remove_history_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
