# Generated by Django 4.2.1 on 2023-05-27 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_sessions_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.PositiveSmallIntegerField(default='45', verbose_name='Длительность мин'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='price',
            field=models.PositiveSmallIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='phone_number',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(70000000000), django.core.validators.MaxValueValidator(79999999999)]),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='row',
            field=models.PositiveSmallIntegerField(verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='seat',
            field=models.PositiveSmallIntegerField(verbose_name='Место'),
        ),
    ]
