# Generated by Django 4.2.1 on 2023-05-29 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_alter_movies_duration_alter_sessions_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='price',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='phone_number',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(70000000000), django.core.validators.MaxValueValidator(79999999999)], verbose_name='Номер телефона'),
        ),
    ]
