# Generated by Django 4.2.1 on 2023-05-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_alter_sessions_price_alter_tickets_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='film_photo',
            field=models.ImageField(upload_to='movies/', verbose_name='Фото'),
        ),
    ]
