# Generated by Django 4.2.1 on 2023-06-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_alter_halls_name_alter_movies_film_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('seat', 'row', 'session')},
        ),
    ]
