# Generated by Django 4.2.1 on 2023-06-01 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_alter_tickets_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_row', models.SmallIntegerField(verbose_name='Номер ряда')),
            ],
        ),
        migrations.RemoveField(
            model_name='halls',
            name='number_seats',
        ),
        migrations.RemoveField(
            model_name='halls',
            name='rows',
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_seat', models.SmallIntegerField(verbose_name='Номер места')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.rows', verbose_name='ID ряда')),
            ],
        ),
        migrations.AddField(
            model_name='rows',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='films.halls', verbose_name='ID зала'),
        ),
        migrations.AddField(
            model_name='halls',
            name='row',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='films.rows', verbose_name='ID ряда'),
            preserve_default=False,
        ),
    ]
