# Generated by Django 4.2.1 on 2023-06-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0022_alter_rows_options_alter_seats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='price',
            field=models.PositiveSmallIntegerField(choices=[('100', '100'), ('150', '150'), ('200', '200'), ('250', '250'), ('300', '300'), ('350', '350'), ('400', '400'), ('450', '450'), ('500', '500')], default='1', verbose_name='Цена'),
        ),
    ]
