# Generated by Django 4.2.1 on 2023-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0024_alter_sessions_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sessions',
            name='end_time',
            field=models.DateTimeField(default='2023-12-15 00:00:00', verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(default='2023-12-15 00:00:00', verbose_name='Время начала'),
        ),
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together={('room', 'start_time', 'film')},
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='start_date',
        ),
    ]
