# Generated by Django 4.2.1 on 2023-06-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0025_alter_sessions_unique_together_sessions_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='end_time',
            field=models.DateTimeField(default='2023-12-15 00:10:00', verbose_name='Время окончания'),
        ),
    ]
