# Generated by Django 4.2.1 on 2023-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0026_alter_sessions_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
    ]
