# Generated by Django 4.2.1 on 2023-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0027_alter_sessions_end_time_alter_sessions_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='filf_genre',
            field=models.CharField(choices=[('Боевик', 'Боевик'), ('Детектив', 'Детектив'), ('Мультфильм', 'Мультфильм'), ('Комедия', 'Комедия'), ('Документальный фильм', 'Документальный фильм'), ('Ужасы ', 'Ужасы'), ('Научная фантастика', 'Научная фантастика'), ('Криминальная драма', 'Криминальная драма')], default='Боевик', max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterUniqueTogether(
            name='rows',
            unique_together={('room', 'number_row')},
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('row', 'number_seat')},
        ),
    ]
