# Generated by Django 4.2.1 on 2023-06-05 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0028_alter_movies_filf_genre_alter_rows_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rows',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rows',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='seats',
            name='number_row',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер ряда'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('number_seat', 'number_row')},
        ),
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together={('start_time', 'film')},
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together={('seat', 'session')},
        ),
        migrations.RemoveField(
            model_name='seats',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='row',
        ),
        migrations.RemoveField(
            model_name='sessions',
            name='room',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='row',
        ),
        migrations.DeleteModel(
            name='Halls',
        ),
        migrations.DeleteModel(
            name='Rows',
        ),
    ]
