# Generated by Django 4.2.1 on 2023-06-06 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0029_alter_rows_unique_together_remove_rows_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seats',
            options={'ordering': ['number_row'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='sessions',
            options={'ordering': ['start_time'], 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AddField(
            model_name='seats',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='films.sessions'),
            preserve_default=False,
        ),
    ]
