# Generated by Django 4.2.1 on 2023-06-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0031_alter_seats_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('number_seat', 'number_row')},
        ),
        migrations.RemoveField(
            model_name='seats',
            name='session',
        ),
    ]
